name: Build the code and Deploy using Surge - Staging
on:
  push:
    branches: [development]

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build project
        if: github.event_name == 'push'
        run: |
           npm run build
           ll