name: Test Code before push to Dev Branch

on:
  pull_request:
    branches: [development]

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci #this is similer to install the npm
      - run: npm run format #it will arrange the code in correct format.
      - run: npm run format:check #This will check the code format
      - run: npm test -- --coverage #This will to the testing of code.
        env:
          CI: true
          
      - name: Open Issue If Workflow Fails
        if: failure() && github.event_name == 'pull_request'
        run: |
          curl --request POST \
          --url https://apt.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
          "title": "Automated issues for commit: ${{ github.sha }}",
          "body": "This issue was automatically created by the GitHub Actions workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
          "assignees": ["${{ github.event.pull_request.user.login }}"]     
          }'

