name: Deploy Application On Prod Along with Release notes and Code Coverange
on:
  push:
    branches: [master]

jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm ci #this is similer to install the npm
      - run: npm run format #This will arrange the code in correct format
      - name: Create a Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}