name: Slack Notification

on:
  release:
    type: [published]

  pull_request:
    branches:
      - "master"
      - "development"

  push:
    branches:
      - "master"
      - "development"

jobs:
  slack-message:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: test
        run: echo ${{ github.head_ref }}
      - name: Pull Request open for Dev/Master Branch
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hi Folks! There is new pull request has open in ${{ github.head_ref }} Branch by User ${{ github.event.pull_request.user.login }}"}' ${{ secrets.SLACK_WEBHOOK }}

      - name: Push in Dev/Master Branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hi Folks! Code Push is done in ${{ github.head_ref }} Branch"}' ${{ secrets.SLACK_WEBHOOK }}
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Approved by: ${{ github.event.pull_request.reviews[0].user.login }}"}' ${{ secrets.SLACK_WEBHOOK }}
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Merged by: ${{ github.event.pull_request.merged_by.login }}"}' ${{ secrets.SLACK_WEBHOOK }}
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Pushed by: ${{ github.event.push.user.login }}"}' ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Message
        if: github.event_name == 'publish' && github.ref == 'refs/heads/master'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World! New Release ${{ github.event.release.tag_name }} is out, <${{ github.event.release.html_url }}|check it out now.>"}' ${{ secrets.SLACK_WEBHOOK }}
        #curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World! New Release ${{ github.event.release.tag_name }} is out, <${{ github.event.release.html_url }}|check it out now.>"}' ${{ secrets.SLACK_WEBHOOK }}
