name: Test, Build and Deploy the Application using Surge on Dev Infra Along with Cache NPM Dependencies & Artifacts Upload.
on:
  pull_request:
    branches: [development]

jobs:
  build-dev:
    if: github.event_name == 'pull_request' #it's mean post pull request gets approved and marged with development branch it workflow will run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm #this is default npm cache path for linux runner
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lok.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          #this is used, if github doesn't find any cache in above key, it will take the older cache from this.

      - name: Use Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci #this is similer to install the npm
      - run: npm run format  #This will arrange the code in correct format        
      - run: npm run format:check #This will check the code format 
      - run: npm test -- --coverage #This will to the testing of code.
        env:
          CI: true
      - name: Upload Test Coverage #it will upload the code test inside the coverage folder named code-coverage in our repo
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage

      - name: Build project
        run: npm run build

      - name: Upload build folder #used for artifacts, if build is success, we will have to build artifacts inside our build folder in repo.
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - uses: actions/download-artifact@v1 #it used to download your artifacts in workspace.
        with:
          name: build
          path: my-artifacts

      - name: install the 'surge' to Deploy the our build
        run: npm install -g surge

      - name: Deploy to Staging
        run: surge --project ./build --domain
          dev-my-react-app-abhiverma001.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }} #To get the login id you can run command locally 'surge whoami'
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }} #To get the tocken you can run the command locally 'surge token' then create the secrets in github repo
